version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: token-bucket-rate-limiter
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"